---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: isotope
description: Based on fedora atomic with Niri and the DankLinux Suite for a more DE-like experience
base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia
image-version: latest

modules:
  - type: os-release
    properties:
      ID: fedora
      # ID_LIKE: fedora
      NAME: Isotope Linux
      PRETTY_NAME: Isotope Linux Image
      DEFAULT_HOSTNAME: isotope

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      masked:
        - NetworkManager-wait-online.service
        - flatpak-add-fedora-repos.service
        - bootc-fetch-apply-updates.timer

  - type: dnf
    repos:
      cleanup: true
      copr:
        - avengemedia/dms-git
        - avengemedia/danklinux
        - scottames/ghostty
    install:
      packages:
        # Scrolling wayland compositor
        - niri
        # run x11 apps in wayland
        - xwayland-satellite
        # toolkit used by dms
        - quickshell-git
        # DE-like for niri
        - dms
        # Matching login screen
        - dms-greeter
        # File chooser
        - xdg-desktop-portal-gnome
        # handle secrets and passwords
        - gnome-keyring
        # handles elvating privileges with password
        - mate-polkit
        # Terminal
        - ghostty
        # TUI file editor and IDE
        - neovim
        # manage containers
        - distrobox
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - nvtop
        - toolbox

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: "3h"

  - type: script
    scripts:
      - install-soar-pkgs.sh

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          name: flathub
          title: Flathub
          install:
            - com.github.tchx84.Flatseal
            - app.zen_browser.zen
            - dev.zed.Zed

  - type: initramfs

  - type: signing
