---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: isotope
description: Based on fedora atomic with Niri and the DankLinux Suite for a more DE-like experience
base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia
image-version: latest

modules:
  - type: os-release
    properties:
      ID: isotope
      ID_LIKE: fedora
      NAME: Isotope Linux
      PRETTY_NAME: Isotope Linux Image
      DEFAULT_HOSTNAME: isotope
  - type: files
    files:
      - source: system
        destination: /
  - type: systemd
    system:
      masked:
        - NetworkManager-wait-online.service
        - flatpak-add-fedora-repos.service
        - bootc-fetch-apply-updates.timer

  - type: dnf
    repos:
      cleanup: true
      copr:
        - avengemedia/dms-git
        - avengemedia/danklinux
        - lihaohong/yazi
        - alternateved/eza
        - atim/starship
        - dejan/rpms
        - peterwu/rendezvous
        - sneexy/zen-browser
        - dejan/lazygit
        - scottames/ghostty
        - shassard/jujutsu
    install:
      packages:
        # Desktop tools
        - niri-git
        - quickshell-git
        - dms
        - dms-greeter
        # # Gnome replacements for what's missing
        # - xdg-desktop-portal-gnome
        # - polkit-gnome
        # - gnome-keyring
        # # Terminal tools
        # - ghostty
        # - fish
        # - lazygit
        # - bat
        # - fzf
        # - starship
        # - ripgrep
        # - ncdu
        # - entr
        # - eza
        # - fastfetch
        # - fd-find
        # - neovim
        # - gh
        # - hyperfine
        # - jq
        # - zoxide
        # - podman-compose
        # - jujutsu
        # - yazi
        # # other tools
        # - zen-browser
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - gnome-disk-utility
        - gnome-system-monitor
        - ark
        - htop
        - vim
        - nvtop
        - toolbox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        repo:
          name: flathub
          title: Flathub

  - type: initramfs

  - type: signing
